version: '3.9'

services:
  finance_api:
    build: .
    container_name: finance_api_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
